POST http://localhost:8080/api/user/add/
Content-Type: application/json

{
  "id":5,
  "email":"test15@gmail.com",
  "dob":"2017-11-11"
}

####
GET http://localhost:8080/api/user/list/

####
POST https://evening-mesa-96335-55ff03eafae8.herokuapp.com/api/user/add/
Content-Type: application/json

{
  "id":1,
  "email":"test14@gmail.com",
  "dob":"2017-11-11"
}

####
GET https://evening-mesa-96335-55ff03eafae8.herokuapp.com/api/user/list/
